#!/usr/bin/env python3
"""Generate README.md: NeetCode 150 progress plus any other solved problems.

Only files committed under solutions/ count (leetcode.nvim creates a file as
soon as you open a problem, so uncommitted = not finished). Optional metadata
as comments anywhere in the solution file:
    // attempts: 3
    // review: yes
    // pattern: design      (only needed for problems outside NeetCode 150)
"""
import json, re, subprocess, urllib.request
from pathlib import Path

ROOT = Path(__file__).parent
CACHE = ROOT / ".difficulty.json"
NC = json.loads((ROOT / "neetcode150.json").read_text(encoding="utf-8"))
FILE_RE = re.compile(r"^solutions/(\d+)\.(.+)\.cpp$")  # leetcode.nvim: <id>.<slug>.cpp
META_RE = re.compile(r"^\s*//\s*(pattern|attempts|review)\s*:\s*(.*)$", re.I)

def git(*args):
    r = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)
    return r.stdout.split("\n") if r.returncode == 0 else []

def fetch_difficulty(slug, cache):
    if slug not in cache:
        try:
            body = json.dumps({"query": "query($s:String!){question(titleSlug:$s){difficulty}}",
                               "variables": {"s": slug}}).encode()
            req = urllib.request.Request("https://leetcode.com/graphql", body, {
                "Content-Type": "application/json", "Referer": "https://leetcode.com",
                "User-Agent": "Mozilla/5.0"})
            cache[slug] = json.load(urllib.request.urlopen(req, timeout=10))["data"]["question"]["difficulty"]
        except Exception:
            return "?"
    return cache[slug]

def solved_files():
    out = {}
    for path in git("ls-files", "solutions"):
        m = FILE_RE.match(path)
        if not m:
            continue
        meta = {}
        text = (ROOT / path).read_text(encoding="utf-8", errors="ignore")
        for line in text.splitlines():
            if (mm := META_RE.match(line)):
                meta[mm[1].lower()] = mm[2].strip()
        dates = [d for d in git("log", "--diff-filter=A", "--format=%as", "--", path) if d]
        out[m[2]] = {"id": int(m[1]), "path": path, "date": dates[-1] if dates else "?", **meta}
    return out

def bar(done, total, width=10):
    n = round(width * done / total) if total else 0
    return "█" * n + "░" * (width - n)

def main():
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    solved = solved_files()
    nc_slugs = {p["slug"] for p in NC}
    link = lambda slug, s: f"[{s['id']}. {slug}]({s['path']})"

    # --- NeetCode 150 grouped by pattern, in roadmap order ---
    groups = {}
    for p in NC:
        groups.setdefault(p["pattern"], []).append(p)
    nc_done = sum(p["slug"] in solved for p in NC)
    nxt = next((p for p in NC if p["slug"] not in solved), None)

    out = ["# LeetCode (C++)", "",
           f"**NeetCode 150:** {nc_done}/150 `{bar(nc_done, 150, 20)}`  ",
           f"**Total solved:** {len(solved)}", ""]
    if nxt:
        out += [f"**Next up:** [{nxt['title']}](https://leetcode.com/problems/{nxt['slug']}/) "
                f"({nxt['pattern']}, {nxt['difficulty']})", ""]

    review = [f"- {link(k, s)}" for k, s in sorted(solved.items(), key=lambda x: x[1]["id"])
              if s.get("review", "").lower() in ("yes", "y", "true")]
    out += ["## To review", "", *(review or ["_Nothing yet_"]), "", "## NeetCode 150", "",
            "| Pattern | Progress | |", "|---|---|---|"]
    for pat, items in groups.items():
        d = sum(p["slug"] in solved for p in items)
        out.append(f"| {pat} | {d}/{len(items)} | `{bar(d, len(items))}` |")
    out.append("")

    for pat, items in groups.items():
        d = sum(p["slug"] in solved for p in items)
        out += [f"<details><summary><b>{pat}</b> ({d}/{len(items)})</summary>", "",
                "| | Problem | Difficulty | Date | Attempts |", "|---|---|---|---|---|"]
        for p in items:
            s = solved.get(p["slug"])
            title = f"[{p['title']}]({s['path']})" if s else \
                    f"[{p['title']}](https://leetcode.com/problems/{p['slug']}/)"
            out.append(f"| {'✅' if s else '⬜'} | {title} | {p['difficulty']} "
                       f"| {s['date'] if s else ''} | {s.get('attempts', '1') if s else ''} |")
        out += ["", "</details>", ""]

    # --- Problems outside NeetCode 150 ---
    extra = sorted(((k, s) for k, s in solved.items() if k not in nc_slugs), key=lambda x: x[1]["id"])
    if extra:
        out += ["## Other problems", "", "| Problem | Difficulty | Pattern | Date | Attempts |", "|---|---|---|---|---|"]
        for k, s in extra:
            out.append(f"| {link(k, s)} | {fetch_difficulty(k, cache)} | {s.get('pattern', '')} "
                       f"| {s['date']} | {s.get('attempts', '1')} |")
        out.append("")
    out.append("<!-- Generated by lc.py, do not edit by hand -->")

    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True))
    (ROOT / "README.md").write_text("\n".join(out), encoding="utf-8")
    print(f"README: NeetCode {nc_done}/150, {len(solved)} solved in total")

if __name__ == "__main__":
    main()
